BEGIN TRANSACTION;
TRUNCATE TABLE tires.order_option;
TRUNCATE TABLE tires.orders RESTART IDENTITY CASCADE;
TRUNCATE TABLE tires.customers RESTART IDENTITY CASCADE;
TRUNCATE TABLE tires.options RESTART IDENTITY CASCADE;
COMMIT;