spring:
  flyway:
    url: jdbc:postgresql://db:5432/tires_db
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/tires_db?currentSchema=tires
    username: postgres
    password: postgres